services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lugatoz-backend-prod
    ports:
      - "8000:8000"
    volumes:
      - backend-db:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    restart: always
    networks:
      - lugatoz-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: lugatoz-frontend-prod
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
    networks:
      - lugatoz-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend-db:

networks:
  lugatoz-network:
    driver: bridge
