services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ozbilig-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-db:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - ozbilig-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ozbilig-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ozbilig-network

volumes:
  backend-db:

networks:
  ozbilig-network:
    driver: bridge
