services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lugatoz-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-db:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - lugatoz-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lugatoz-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - lugatoz-network

volumes:
  backend-db:

networks:
  lugatoz-network:
    driver: bridge
